name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Before submitting:
        - Search [existing issues](https://github.com/alnah/go-md2pdf/issues) for similar requests
        - Check [Known Limitations](https://github.com/alnah/go-md2pdf#known-limitations) for intentional design decisions

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Blocking my use case

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Examples, mockups, references
