package main

import (
	"fmt"
	"io"
	"strings"
)

// generateBash generates Bash completion script.
func generateBash(w io.Writer, cliName string) error {
	var b strings.Builder
	funcName := canonicalizeShellFuncName(cliName)

	fmt.Fprintf(&b, "# Bash completion for %s\n", cliName)
	fmt.Fprintf(&b, "# Generated by %s completion bash\n\n", cliName)
	fmt.Fprintf(&b, "_%s_completions() {\n", funcName)
	b.WriteString("    local cur prev words cword\n")
	b.WriteString("    _init_completion || return\n\n")
	b.WriteString("    local commands=\"")

	for i, cmd := range getCommands() {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(cmd.Name)
	}
	b.WriteString("\"\n\n")
	b.WriteString("    # Handle completion based on position and previous word\n")
	b.WriteString("    case \"${cword}\" in\n")
	b.WriteString("        1)\n")
	b.WriteString("            COMPREPLY=($(compgen -W \"${commands}\" -- \"${cur}\"))\n")
	b.WriteString("            return\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n\n")
	fmt.Fprintf(&b, "    # Get the command (first argument after %s)\n", cliName)
	b.WriteString("    local cmd=\"${words[1]}\"\n\n")
	b.WriteString("    case \"${cmd}\" in\n")

	for _, cmd := range getCommands() {
		fmt.Fprintf(&b, "        %s)\n", cmd.Name)
		if cmd.Name == "help" {
			b.WriteString("            COMPREPLY=($(compgen -W \"${commands}\" -- \"${cur}\"))\n")
			b.WriteString("            return\n")
			b.WriteString("            ;;\n")
			continue
		}
		if cmd.Name == "completion" {
			b.WriteString("            COMPREPLY=($(compgen -W \"bash zsh fish powershell\" -- \"${cur}\"))\n")
			b.WriteString("            return\n")
			b.WriteString("            ;;\n")
			continue
		}
		if len(cmd.Flags) == 0 && !cmd.TakesFiles {
			b.WriteString("            return\n")
			b.WriteString("            ;;\n")
			continue
		}
		generateBashCommandCase(&b, cmd, funcName)
		b.WriteString("            ;;\n")
	}

	b.WriteString("    esac\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "_%s_complete_files() {\n", funcName)
	b.WriteString("    local patterns=\"$1\"\n")
	b.WriteString("    local IFS=','\n")
	b.WriteString("    local result=()\n")
	b.WriteString("    for pattern in $patterns; do\n")
	b.WriteString("        local files=$(compgen -f -- \"${cur}\" 2>/dev/null | grep -E \"\\.(${pattern#*.})$\" 2>/dev/null)\n")
	b.WriteString("        if [[ -n \"$files\" ]]; then\n")
	b.WriteString("            result+=($files)\n")
	b.WriteString("        fi\n")
	b.WriteString("    done\n")
	b.WriteString("    local dirs=$(compgen -d -- \"${cur}\" 2>/dev/null)\n")
	b.WriteString("    if [[ -n \"$dirs\" ]]; then\n")
	b.WriteString("        result+=($dirs)\n")
	b.WriteString("    fi\n")
	b.WriteString("    COMPREPLY=(${result[@]})\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "_%s_complete_dirs() {\n", funcName)
	b.WriteString("    COMPREPLY=($(compgen -d -- \"${cur}\"))\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "complete -F _%s_completions %s\n", funcName, cliName)

	_, err := w.Write([]byte(b.String()))
	return err
}

// generateBashCommandCase generates the case body for a command.
func generateBashCommandCase(b *strings.Builder, cmd commandDef, funcName string) {
	var allFlags []string
	enumFlags := make(map[string][]string)
	fileFlags := make(map[string]string)
	var dirFlags []string

	for _, f := range cmd.Flags {
		allFlags = append(allFlags, "--"+f.Long)
		if f.Short != "" {
			allFlags = append(allFlags, "-"+f.Short)
		}

		switch f.Type {
		case flagEnum:
			enumFlags["--"+f.Long] = f.Values
			if f.Short != "" {
				enumFlags["-"+f.Short] = f.Values
			}
		case flagFile:
			fileFlags["--"+f.Long] = f.FileGlob
			if f.Short != "" {
				fileFlags["-"+f.Short] = f.FileGlob
			}
		case flagDir:
			dirFlags = append(dirFlags, "--"+f.Long)
			if f.Short != "" {
				dirFlags = append(dirFlags, "-"+f.Short)
			}
		}
	}

	b.WriteString("            case \"${prev}\" in\n")
	for flag, values := range enumFlags {
		fmt.Fprintf(b, "                %s)\n", flag)
		fmt.Fprintf(b, "                    COMPREPLY=($(compgen -W \"%s\" -- \"${cur}\"))\n", strings.Join(values, " "))
		b.WriteString("                    return\n")
		b.WriteString("                    ;;\n")
	}
	for flag, glob := range fileFlags {
		fmt.Fprintf(b, "                %s)\n", flag)
		fmt.Fprintf(b, "                    _%s_complete_files \"%s\"\n", funcName, glob)
		b.WriteString("                    return\n")
		b.WriteString("                    ;;\n")
	}
	for _, flag := range dirFlags {
		fmt.Fprintf(b, "                %s)\n", flag)
		fmt.Fprintf(b, "                    _%s_complete_dirs\n", funcName)
		b.WriteString("                    return\n")
		b.WriteString("                    ;;\n")
	}
	b.WriteString("            esac\n\n")
	b.WriteString("            if [[ \"${cur}\" == -* ]]; then\n")
	fmt.Fprintf(b, "                COMPREPLY=($(compgen -W \"%s\" -- \"${cur}\"))\n", strings.Join(allFlags, " "))
	b.WriteString("            else\n")
	if cmd.TakesFiles && cmd.FilePattern != "" {
		fmt.Fprintf(b, "                _%s_complete_files \"%s\"\n", funcName, cmd.FilePattern)
	} else {
		b.WriteString("                COMPREPLY=()\n")
	}
	b.WriteString("            fi\n")
}
